//! Generated protobuf code for gRPC backend communication
//!
//! This module will contain the generated code from backend.proto
//! Run `cargo build` to generate the code via build.rs

// Include the generated protobuf code
// The file will be generated by tonic-build during compilation
#[cfg(feature = "grpc")]
tonic::include_proto!("imagebackend");

// For now, we'll define placeholder types that match the proto definitions
// These will be replaced by the generated code when building with gRPC support

#[cfg(not(feature = "grpc"))]
pub mod imagebackend {
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct GenerateRequest {
        pub prompt: String,
        pub negative_prompt: String,
        pub n: i32,
        pub width: i32,
        pub height: i32,
        pub model: String,
        pub seed: i64,
        pub guidance_scale: f32,
        pub num_inference_steps: i32,
        pub response_format: String,
        pub extra_params: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct ImageData {
        pub b64_json: String,
        pub url: String,
        pub revised_prompt: String,
        pub seed: i64,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct GenerateResponse {
        pub created: i64,
        pub data: Vec<ImageData>,
        pub model: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct HealthCheckRequest {}

    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct HealthCheckResponse {
        pub healthy: bool,
        pub message: String,
        pub available_models: Vec<String>,
    }
}

