# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x62\x61\x63kend.proto\x12\x0cimagebackend"\xe8\x01\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\x12\t\n\x01n\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\r\n\x05model\x18\x06 \x01(\t\x12\x0c\n\x04seed\x18\x07 \x01(\x03\x12\x16\n\x0eguidance_scale\x18\x08 \x01(\x02\x12\x1b\n\x13num_inference_steps\x18\t \x01(\x05\x12\x17\n\x0fresponse_format\x18\n \x01(\t\x12\x14\n\x0c\x65xtra_params\x18\x0b \x01(\t"Q\n\tImageData\x12\x10\n\x08\x62\x36\x34_json\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x16\n\x0erevised_prompt\x18\x03 \x01(\t\x12\x0c\n\x04seed\x18\x04 \x01(\x03"[\n\x10GenerateResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x03\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x17.imagebackend.ImageData\x12\r\n\x05model\x18\x03 \x01(\t"\x14\n\x12HealthCheckRequest"R\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x10\x61vailable_models\x18\x03 \x03(\t2\xb5\x01\n\x13ImageBackendService\x12M\n\x08Generate\x12\x1d.imagebackend.GenerateRequest\x1a\x1e.imagebackend.GenerateResponse"\x00\x12O\n\x0bHealthCheck\x12 .imagebackend.HealthCheckRequest\x1a!.imagebackend.HealthCheckResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imagebackend_pb2", globals())

