# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imagebackend_pb2 as imagebackend__pb2


class ImageBackendServiceStub(object):
    """Image generation backend service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
            "/imagebackend.ImageBackendService/Generate",
            request_serializer=imagebackend__pb2.GenerateRequest.SerializeToString,
            response_deserializer=imagebackend__pb2.GenerateResponse.FromString,
        )
        self.HealthCheck = channel.unary_unary(
            "/imagebackend.ImageBackendService/HealthCheck",
            request_serializer=imagebackend__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=imagebackend__pb2.HealthCheckResponse.FromString,
        )


class ImageBackendServiceServicer(object):
    """Image generation backend service"""

    def Generate(self, request, context):
        """Generate images from a text prompt"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check endpoint"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ImageBackendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Generate": grpc.unary_unary_rpc_method_handler(
            servicer.Generate,
            request_deserializer=imagebackend__pb2.GenerateRequest.FromString,
            response_serializer=imagebackend__pb2.GenerateResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=imagebackend__pb2.HealthCheckRequest.FromString,
            response_serializer=imagebackend__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "imagebackend.ImageBackendService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))

